import './globals.css';

export const metadata = {
  title: 'Full Stack Next.JS',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-[#121212] text-white">
        {children}
      </body>
    </html>
  )
};